# This is a basic workflow to help you get started with Actions

name: Build and Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'tag number'     
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Npm dependencies
        run: npm install
        
      # Runs a set of commands using the runners shell
      - name: Npm build
        run: npm run build
            
       # Runs a set of commands using the runners shell
      - name: Zip disk folder
        run: |
          cd ./dist/LeetcodeSessionManager
          zip -r ../../LeetcodeSessionManager-$(node -p "require('./package.json').version").zip .
                   
      - name: 'Upload Build Artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./LeetcodeSessionManager*.zip
          
  release-content:
    name: 'Create GitHub Release'
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    steps:      
      - name: 'Download Presentation Artifacts'
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./LeetcodeSessionManager*.zip       
          tag_name: v${{ github.run_number }}
          name: Release V${{ github.run_number }}
