# This is a basic workflow to help you get started with Actions

name: Build and Release

# Controls when the workflow will run
on:
  push:
    branches:
      - master
 
  pull_request:
    branches:
      - master
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag number'     
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: 'Build and release Zip'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Npm dependencies
        run: npm install
        
      # Runs a set of commands using the runners shell
      - name: Npm build
        run: npm run build
            
       # Runs a set of commands using the runners shell
      - name: Zip extension
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          mv LICENSE ./dist/LeetcodeSessionManager
          cd ./dist/LeetcodeSessionManager
          sed  -i '/version/s/[^.]*$/'"${{ github.event.inputs.tag }}\"/" manifest.json
          zip -r ../../LeetcodeSessionManager-${{ github.event.inputs.tag }}.zip .
                   
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          files: ./LeetcodeSessionManager*.zip       
          tag_name: v${{ github.run_number }}
          name: Release V${{ github.event.inputs.tag }}
